Main Game logic
KerronKing/Tic-Tac-Toe-JS pull request #1
Opened 2020-01-02 22:20 UTC by KerronKing

In this project, we:

- Created the skeleton of the page with HTML and CSS.
- Added a form to collect player data.
- Created an array to hold player information and the function that renders the game board.
- Added event listeners to update the game board with player symbols.
- Added the logic to check if a game is won/lost or drawn.
- Added the ability for the user to reset the game at any point.
- Edited overall styling.

2020-01-02 23:36 UTC, bellom commented on app.js
> +// Global Array to store player objects
**Kindly remove commented code, you can always use git history to access previous code right :slightly_smiling_face:**

2020-01-02 23:39 UTC, KerronKing commented
Good night Oluwaseun. All comments have been removed.

2020-01-02 23:59 UTC, bellom requested changes
## Hi Team :clap: 
#### Awesome job so far guys!! :+1: 
#### You have done wonderfully well, you passed almost all checklist for this project :+1: 
1. we have this little bug; player with sign X already won, but no sign of winning the game, as you can see below;
![image](https://user-images.githubusercontent.com/31897434/71700097-00972700-2dc3-11ea-94ae-2f6316b164de.png)

**Kindly re-submit for review after making all necessary changes :slightly_smiling_face: Thumps -up await you....**

Best,

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2020-01-02 23:59 UTC, bellom commented on app.js
> +let players = [];
**We can call `players` anywhere in this code, we told not to use global code right ?**

It doesn't use `global` code - encapsulate logic inside modules or factories ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/tic_tac_toe/global_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/tic-tac-toe-javascript))

2020-01-03 19:41 UTC, KerronKing commented
Good Day Oluwaseun. All suggested changes were made. We look forward to a fresh review.

Thanks!

2020-01-04 00:20 UTC, bellom approved these changes
## Hi Team :clap: 

**Great work making all the necessary corrections from the previous review.**

## Congratulation :+1:  
_Go ahead and merge to dev and don't forget to submit project completion form.
Goodluck in the next project :slightly_smiling_face:_ 

Best,

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2020-01-06 13:18 UTC, merged